language: php

php:
  - 5.6

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'CREATE TABLE `test`.`blog` ( `id` int(11) NOT NULL AUTO_INCREMENT, `title` varchar(100) NOT NULL, `body` text, `reads` int(11) NOT NULL DEFAULT '0', `rate` float(6,2) DEFAULT '0.00', `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8; '

before_script:
  - composer self-update
  - composer install --no-interaction
  - composer dumpautoload

script:
  - vendor/bin/phpunit -c phpunit.xml --coverage-text

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_USER=test
    - DB_PASS=
    - DB_NAME=test
